### ISSUE TITLE
Add 'mirror' controls in manipulation plugin

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#453]
Can also be grouped with zoom and rotate. Should be able to mirror left-right and top-bottom.

Use case: I want to be able to read this:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/163183/44480203-f7c90980-a642-11e8-957e-616a435fcc77.png">

**Comment by EricHanLiu** [comment]
Added mirror controls.

Uses css instead of altering image data like the other tools, which is much easier for compatibility with zoom and rotate

**Comment by ahankinson** [comment]
Mirror vertically sometimes mirrors horizontally. (Happened once, but I can't seem to make it happen again)

If you mirror first, then rotate, you get an overlay of the image on top of itself. 

<img width="988" alt="image" src="https://user-images.githubusercontent.com/163183/44581733-3247b900-a79f-11e8-9361-754fad356223.png">

**Comment by EricHanLiu** [comment]
I can't reproduce this issue

Tried with development and production build files, a larger screen, and safari + firefox

**Comment by EricHanLiu** [comment]
Closing since I can't replicate this at all, perhaps it was fixed by the latest change (which also fixed the vertical mirror sometimes mirroring horizontally)

**Comment by ahankinson** [comment]
It's still happening:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/163183/44717519-7ac3e700-aabd-11e8-8500-205360ae89ea.png">

I'm on Chrome.

**Comment by EricHanLiu** [comment]
Should be fixed now, mirror and rotation both use CSS transforms instead of redrawing the canvas. Seems faster as well
